# Gitolite-Golang 配置文件
repo_base: "****/gitolite/repositories"
gerrit_url: "******"
gerrit_user: "******"
gerrit_remote_url: "******"
gerrit_api_token: "******"
authorized_keys: "****/.ssh/authorized_keys"
# 权限和钩子配置
access_config: "****/.gitolite/conf/gitolite.conf"
hooks_dir: "****/.gitolite/hooks"

log:
  path: "****/gitolite/gitolite-shell.log"
  level: DEBUG  # 可选值: INFO, WARN, ERROR
  rotation: daily  # 日志轮转周期: daily 或 weekly
  compress: true   # 是否压缩旧日志
  max_age: 30      # 日志保留天数
audit:
  enabled: true  # 是否启用审计功能
  log_path: "****/gitolite/audit.log"  # 审计日志文件路径
  console_out: true  # 是否在控制台输出结构化访问信息

# Gerrit免权限检查白名单配置，使用在replication场景
whitelist:
  users:  # 跳过权限检查的用户列表
    - "gerrit-replication"
    - "git"