# Gitolite-Golang 配置文件

# 基础配置
repo_base: /home/git/repositories
gerrit_url: https://gerrit.url.com
gerrit_user: gitadmin
gerrit_remote_url: ssh://gitadmin@gerrit.url.com:29418
gerrit_api_token: XXXXX
authorized_keys: /home/git/.ssh/authorized_keys

# 权限和钩子配置
access_config: /home/git/.gitolite/conf/gitolite.conf
hooks_dir: /home/git/.gitolite/hooks

# 日志配置
log:
  path: /home/git/gitolite/gitolite-shell.log
  level: INFO  # 可选值: INFO, WARN, ERROR
  rotation: daily  # 日志轮转周期: daily 或 weekly
  compress: true   # 是否压缩旧日志
  max_age: 30      # 日志保留天数